doctrine:
  dbal:
    dbname: '%env(MYSQL_DATABASE)%'
    host: '%env(MYSQL_HOST)%'
    port: 3306
    user: '%env(MYSQL_USER)%'
    password: '%env(MYSQL_PASSWORD)%'
    driver: '%env(MYSQL_DRIVER)%'

    mapping_types:
      enum: string

    # ignore bitrix tables (prefix b_)
    schema_filter: ~^(?!b\_)~ #((?!b\_)|b_file$)

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    server_version: '5.7'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
